version: "3"

services:
  app:
    environment:
      DB_HOST: db
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/app
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - ./pg_data:/var/lib/postgresql/data
